// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages-xcosh.proto

package trezor

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// *
// Request: Ask device for public key corresponding to address_n path
// @start
// @next XcoshPublicKey
// @next Failure
type XcoshGetPublicKey struct {
	AddressN             []uint32 `protobuf:"varint,1,rep,name=address_n,json=addressN" json:"address_n,omitempty"`
	ShowDisplay          *bool    `protobuf:"varint,2,opt,name=show_display,json=showDisplay" json:"show_display,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *XcoshGetPublicKey) Reset()         { *m = XcoshGetPublicKey{} }
func (m *XcoshGetPublicKey) String() string { return proto.CompactTextString(m) }
func (*XcoshGetPublicKey) ProtoMessage()    {}
func (*XcoshGetPublicKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb33f46ba915f15c, []int{0}
}

func (m *XcoshGetPublicKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XcoshGetPublicKey.Unmarshal(m, b)
}
func (m *XcoshGetPublicKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XcoshGetPublicKey.Marshal(b, m, deterministic)
}
func (m *XcoshGetPublicKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XcoshGetPublicKey.Merge(m, src)
}
func (m *XcoshGetPublicKey) XXX_Size() int {
	return xxx_messageInfo_XcoshGetPublicKey.Size(m)
}
func (m *XcoshGetPublicKey) XXX_DiscardUnknown() {
	xxx_messageInfo_XcoshGetPublicKey.DiscardUnknown(m)
}

var xxx_messageInfo_XcoshGetPublicKey proto.InternalMessageInfo

func (m *XcoshGetPublicKey) GetAddressN() []uint32 {
	if m != nil {
		return m.AddressN
	}
	return nil
}

func (m *XcoshGetPublicKey) GetShowDisplay() bool {
	if m != nil && m.ShowDisplay != nil {
		return *m.ShowDisplay
	}
	return false
}

// *
// Response: Contains public key derived from device private seed
// @end
type XcoshPublicKey struct {
	Node                 *HDNodeType `protobuf:"bytes,1,opt,name=node" json:"node,omitempty"`
	Xpub                 *string     `protobuf:"bytes,2,opt,name=xpub" json:"xpub,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *XcoshPublicKey) Reset()         { *m = XcoshPublicKey{} }
func (m *XcoshPublicKey) String() string { return proto.CompactTextString(m) }
func (*XcoshPublicKey) ProtoMessage()    {}
func (*XcoshPublicKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb33f46ba915f15c, []int{1}
}

func (m *XcoshPublicKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XcoshPublicKey.Unmarshal(m, b)
}
func (m *XcoshPublicKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XcoshPublicKey.Marshal(b, m, deterministic)
}
func (m *XcoshPublicKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XcoshPublicKey.Merge(m, src)
}
func (m *XcoshPublicKey) XXX_Size() int {
	return xxx_messageInfo_XcoshPublicKey.Size(m)
}
func (m *XcoshPublicKey) XXX_DiscardUnknown() {
	xxx_messageInfo_XcoshPublicKey.DiscardUnknown(m)
}

var xxx_messageInfo_XcoshPublicKey proto.InternalMessageInfo

func (m *XcoshPublicKey) GetNode() *HDNodeType {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *XcoshPublicKey) GetXpub() string {
	if m != nil && m.Xpub != nil {
		return *m.Xpub
	}
	return ""
}

// *
// Request: Ask device for Xcosh address corresponding to address_n path
// @start
// @next XcoshAddress
// @next Failure
type XcoshGetAddress struct {
	AddressN             []uint32 `protobuf:"varint,1,rep,name=address_n,json=addressN" json:"address_n,omitempty"`
	ShowDisplay          *bool    `protobuf:"varint,2,opt,name=show_display,json=showDisplay" json:"show_display,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *XcoshGetAddress) Reset()         { *m = XcoshGetAddress{} }
func (m *XcoshGetAddress) String() string { return proto.CompactTextString(m) }
func (*XcoshGetAddress) ProtoMessage()    {}
func (*XcoshGetAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb33f46ba915f15c, []int{2}
}

func (m *XcoshGetAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XcoshGetAddress.Unmarshal(m, b)
}
func (m *XcoshGetAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XcoshGetAddress.Marshal(b, m, deterministic)
}
func (m *XcoshGetAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XcoshGetAddress.Merge(m, src)
}
func (m *XcoshGetAddress) XXX_Size() int {
	return xxx_messageInfo_XcoshGetAddress.Size(m)
}
func (m *XcoshGetAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_XcoshGetAddress.DiscardUnknown(m)
}

var xxx_messageInfo_XcoshGetAddress proto.InternalMessageInfo

func (m *XcoshGetAddress) GetAddressN() []uint32 {
	if m != nil {
		return m.AddressN
	}
	return nil
}

func (m *XcoshGetAddress) GetShowDisplay() bool {
	if m != nil && m.ShowDisplay != nil {
		return *m.ShowDisplay
	}
	return false
}

// *
// Response: Contains an Xcosh address derived from device private seed
// @end
type XcoshAddress struct {
	AddressBin           []byte   `protobuf:"bytes,1,opt,name=addressBin" json:"addressBin,omitempty"`
	AddressHex           *string  `protobuf:"bytes,2,opt,name=addressHex" json:"addressHex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *XcoshAddress) Reset()         { *m = XcoshAddress{} }
func (m *XcoshAddress) String() string { return proto.CompactTextString(m) }
func (*XcoshAddress) ProtoMessage()    {}
func (*XcoshAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb33f46ba915f15c, []int{3}
}

func (m *XcoshAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XcoshAddress.Unmarshal(m, b)
}
func (m *XcoshAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XcoshAddress.Marshal(b, m, deterministic)
}
func (m *XcoshAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XcoshAddress.Merge(m, src)
}
func (m *XcoshAddress) XXX_Size() int {
	return xxx_messageInfo_XcoshAddress.Size(m)
}
func (m *XcoshAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_XcoshAddress.DiscardUnknown(m)
}

var xxx_messageInfo_XcoshAddress proto.InternalMessageInfo

func (m *XcoshAddress) GetAddressBin() []byte {
	if m != nil {
		return m.AddressBin
	}
	return nil
}

func (m *XcoshAddress) GetAddressHex() string {
	if m != nil && m.AddressHex != nil {
		return *m.AddressHex
	}
	return ""
}

// *
// Request: Ask device to sign transaction
// All fields are optional from the protocol's point of view. Each field defaults to value `0` if missing.
// Note: the first at most 1024 bytes of data MUST be transmitted as part of this message.
// @start
// @next XcoshTxRequest
// @next Failure
type XcoshSignTx struct {
	AddressN             []uint32 `protobuf:"varint,1,rep,name=address_n,json=addressN" json:"address_n,omitempty"`
	Nonce                []byte   `protobuf:"bytes,2,opt,name=nonce" json:"nonce,omitempty"`
	GasPrice             []byte   `protobuf:"bytes,3,opt,name=gas_price,json=gasPrice" json:"gas_price,omitempty"`
	GasLimit             []byte   `protobuf:"bytes,4,opt,name=gas_limit,json=gasLimit" json:"gas_limit,omitempty"`
	ToBin                []byte   `protobuf:"bytes,5,opt,name=toBin" json:"toBin,omitempty"`
	ToHex                *string  `protobuf:"bytes,11,opt,name=toHex" json:"toHex,omitempty"`
	Value                []byte   `protobuf:"bytes,6,opt,name=value" json:"value,omitempty"`
	DataInitialChunk     []byte   `protobuf:"bytes,7,opt,name=data_initial_chunk,json=dataInitialChunk" json:"data_initial_chunk,omitempty"`
	DataLength           *uint32  `protobuf:"varint,8,opt,name=data_length,json=dataLength" json:"data_length,omitempty"`
	ChainId              *uint32  `protobuf:"varint,9,opt,name=chain_id,json=chainId" json:"chain_id,omitempty"`
	TxType               *uint32  `protobuf:"varint,10,opt,name=tx_type,json=txType" json:"tx_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *XcoshSignTx) Reset()         { *m = XcoshSignTx{} }
func (m *XcoshSignTx) String() string { return proto.CompactTextString(m) }
func (*XcoshSignTx) ProtoMessage()    {}
func (*XcoshSignTx) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb33f46ba915f15c, []int{4}
}

func (m *XcoshSignTx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XcoshSignTx.Unmarshal(m, b)
}
func (m *XcoshSignTx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XcoshSignTx.Marshal(b, m, deterministic)
}
func (m *XcoshSignTx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XcoshSignTx.Merge(m, src)
}
func (m *XcoshSignTx) XXX_Size() int {
	return xxx_messageInfo_XcoshSignTx.Size(m)
}
func (m *XcoshSignTx) XXX_DiscardUnknown() {
	xxx_messageInfo_XcoshSignTx.DiscardUnknown(m)
}

var xxx_messageInfo_XcoshSignTx proto.InternalMessageInfo

func (m *XcoshSignTx) GetAddressN() []uint32 {
	if m != nil {
		return m.AddressN
	}
	return nil
}

func (m *XcoshSignTx) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *XcoshSignTx) GetGasPrice() []byte {
	if m != nil {
		return m.GasPrice
	}
	return nil
}

func (m *XcoshSignTx) GetGasLimit() []byte {
	if m != nil {
		return m.GasLimit
	}
	return nil
}

func (m *XcoshSignTx) GetToBin() []byte {
	if m != nil {
		return m.ToBin
	}
	return nil
}

func (m *XcoshSignTx) GetToHex() string {
	if m != nil && m.ToHex != nil {
		return *m.ToHex
	}
	return ""
}

func (m *XcoshSignTx) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *XcoshSignTx) GetDataInitialChunk() []byte {
	if m != nil {
		return m.DataInitialChunk
	}
	return nil
}

func (m *XcoshSignTx) GetDataLength() uint32 {
	if m != nil && m.DataLength != nil {
		return *m.DataLength
	}
	return 0
}

func (m *XcoshSignTx) GetChainId() uint32 {
	if m != nil && m.ChainId != nil {
		return *m.ChainId
	}
	return 0
}

func (m *XcoshSignTx) GetTxType() uint32 {
	if m != nil && m.TxType != nil {
		return *m.TxType
	}
	return 0
}

// *
// Response: Device asks for more data from transaction payload, or returns the signature.
// If data_length is set, device awaits that many more bytes of payload.
// Otherwise, the signature_* fields contain the computed transaction signature. All three fields will be present.
// @end
// @next XcoshTxAck
type XcoshTxRequest struct {
	DataLength           *uint32  `protobuf:"varint,1,opt,name=data_length,json=dataLength" json:"data_length,omitempty"`
	SignatureV           *uint32  `protobuf:"varint,2,opt,name=signature_v,json=signatureV" json:"signature_v,omitempty"`
	SignatureR           []byte   `protobuf:"bytes,3,opt,name=signature_r,json=signatureR" json:"signature_r,omitempty"`
	SignatureS           []byte   `protobuf:"bytes,4,opt,name=signature_s,json=signatureS" json:"signature_s,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *XcoshTxRequest) Reset()         { *m = XcoshTxRequest{} }
func (m *XcoshTxRequest) String() string { return proto.CompactTextString(m) }
func (*XcoshTxRequest) ProtoMessage()    {}
func (*XcoshTxRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb33f46ba915f15c, []int{5}
}

func (m *XcoshTxRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XcoshTxRequest.Unmarshal(m, b)
}
func (m *XcoshTxRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XcoshTxRequest.Marshal(b, m, deterministic)
}
func (m *XcoshTxRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XcoshTxRequest.Merge(m, src)
}
func (m *XcoshTxRequest) XXX_Size() int {
	return xxx_messageInfo_XcoshTxRequest.Size(m)
}
func (m *XcoshTxRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_XcoshTxRequest.DiscardUnknown(m)
}

var xxx_messageInfo_XcoshTxRequest proto.InternalMessageInfo

func (m *XcoshTxRequest) GetDataLength() uint32 {
	if m != nil && m.DataLength != nil {
		return *m.DataLength
	}
	return 0
}

func (m *XcoshTxRequest) GetSignatureV() uint32 {
	if m != nil && m.SignatureV != nil {
		return *m.SignatureV
	}
	return 0
}

func (m *XcoshTxRequest) GetSignatureR() []byte {
	if m != nil {
		return m.SignatureR
	}
	return nil
}

func (m *XcoshTxRequest) GetSignatureS() []byte {
	if m != nil {
		return m.SignatureS
	}
	return nil
}

// *
// Request: Transaction payload data.
// @next XcoshTxRequest
type XcoshTxAck struct {
	DataChunk            []byte   `protobuf:"bytes,1,opt,name=data_chunk,json=dataChunk" json:"data_chunk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *XcoshTxAck) Reset()         { *m = XcoshTxAck{} }
func (m *XcoshTxAck) String() string { return proto.CompactTextString(m) }
func (*XcoshTxAck) ProtoMessage()    {}
func (*XcoshTxAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb33f46ba915f15c, []int{6}
}

func (m *XcoshTxAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XcoshTxAck.Unmarshal(m, b)
}
func (m *XcoshTxAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XcoshTxAck.Marshal(b, m, deterministic)
}
func (m *XcoshTxAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XcoshTxAck.Merge(m, src)
}
func (m *XcoshTxAck) XXX_Size() int {
	return xxx_messageInfo_XcoshTxAck.Size(m)
}
func (m *XcoshTxAck) XXX_DiscardUnknown() {
	xxx_messageInfo_XcoshTxAck.DiscardUnknown(m)
}

var xxx_messageInfo_XcoshTxAck proto.InternalMessageInfo

func (m *XcoshTxAck) GetDataChunk() []byte {
	if m != nil {
		return m.DataChunk
	}
	return nil
}

// *
// Request: Ask device to sign message
// @start
// @next XcoshMessageSignature
// @next Failure
type XcoshSignMessage struct {
	AddressN             []uint32 `protobuf:"varint,1,rep,name=address_n,json=addressN" json:"address_n,omitempty"`
	Message              []byte   `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *XcoshSignMessage) Reset()         { *m = XcoshSignMessage{} }
func (m *XcoshSignMessage) String() string { return proto.CompactTextString(m) }
func (*XcoshSignMessage) ProtoMessage()    {}
func (*XcoshSignMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb33f46ba915f15c, []int{7}
}

func (m *XcoshSignMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XcoshSignMessage.Unmarshal(m, b)
}
func (m *XcoshSignMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XcoshSignMessage.Marshal(b, m, deterministic)
}
func (m *XcoshSignMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XcoshSignMessage.Merge(m, src)
}
func (m *XcoshSignMessage) XXX_Size() int {
	return xxx_messageInfo_XcoshSignMessage.Size(m)
}
func (m *XcoshSignMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_XcoshSignMessage.DiscardUnknown(m)
}

var xxx_messageInfo_XcoshSignMessage proto.InternalMessageInfo

func (m *XcoshSignMessage) GetAddressN() []uint32 {
	if m != nil {
		return m.AddressN
	}
	return nil
}

func (m *XcoshSignMessage) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

// *
// Response: Signed message
// @end
type XcoshMessageSignature struct {
	AddressBin           []byte   `protobuf:"bytes,1,opt,name=addressBin" json:"addressBin,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=signature" json:"signature,omitempty"`
	AddressHex           *string  `protobuf:"bytes,3,opt,name=addressHex" json:"addressHex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *XcoshMessageSignature) Reset()         { *m = XcoshMessageSignature{} }
func (m *XcoshMessageSignature) String() string { return proto.CompactTextString(m) }
func (*XcoshMessageSignature) ProtoMessage()    {}
func (*XcoshMessageSignature) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb33f46ba915f15c, []int{8}
}

func (m *XcoshMessageSignature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XcoshMessageSignature.Unmarshal(m, b)
}
func (m *XcoshMessageSignature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XcoshMessageSignature.Marshal(b, m, deterministic)
}
func (m *XcoshMessageSignature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XcoshMessageSignature.Merge(m, src)
}
func (m *XcoshMessageSignature) XXX_Size() int {
	return xxx_messageInfo_XcoshMessageSignature.Size(m)
}
func (m *XcoshMessageSignature) XXX_DiscardUnknown() {
	xxx_messageInfo_XcoshMessageSignature.DiscardUnknown(m)
}

var xxx_messageInfo_XcoshMessageSignature proto.InternalMessageInfo

func (m *XcoshMessageSignature) GetAddressBin() []byte {
	if m != nil {
		return m.AddressBin
	}
	return nil
}

func (m *XcoshMessageSignature) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *XcoshMessageSignature) GetAddressHex() string {
	if m != nil && m.AddressHex != nil {
		return *m.AddressHex
	}
	return ""
}

// *
// Request: Ask device to verify message
// @start
// @next Success
// @next Failure
type XcoshVerifyMessage struct {
	AddressBin           []byte   `protobuf:"bytes,1,opt,name=addressBin" json:"addressBin,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=signature" json:"signature,omitempty"`
	Message              []byte   `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	AddressHex           *string  `protobuf:"bytes,4,opt,name=addressHex" json:"addressHex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *XcoshVerifyMessage) Reset()         { *m = XcoshVerifyMessage{} }
func (m *XcoshVerifyMessage) String() string { return proto.CompactTextString(m) }
func (*XcoshVerifyMessage) ProtoMessage()    {}
func (*XcoshVerifyMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb33f46ba915f15c, []int{9}
}

func (m *XcoshVerifyMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XcoshVerifyMessage.Unmarshal(m, b)
}
func (m *XcoshVerifyMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XcoshVerifyMessage.Marshal(b, m, deterministic)
}
func (m *XcoshVerifyMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XcoshVerifyMessage.Merge(m, src)
}
func (m *XcoshVerifyMessage) XXX_Size() int {
	return xxx_messageInfo_XcoshVerifyMessage.Size(m)
}
func (m *XcoshVerifyMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_XcoshVerifyMessage.DiscardUnknown(m)
}

var xxx_messageInfo_XcoshVerifyMessage proto.InternalMessageInfo

func (m *XcoshVerifyMessage) GetAddressBin() []byte {
	if m != nil {
		return m.AddressBin
	}
	return nil
}

func (m *XcoshVerifyMessage) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *XcoshVerifyMessage) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *XcoshVerifyMessage) GetAddressHex() string {
	if m != nil && m.AddressHex != nil {
		return *m.AddressHex
	}
	return ""
}

func init() {
	proto.RegisterType((*XcoshGetPublicKey)(nil), "hw.trezor.messages.xcosh.XcoshGetPublicKey")
	proto.RegisterType((*XcoshPublicKey)(nil), "hw.trezor.messages.xcosh.XcoshPublicKey")
	proto.RegisterType((*XcoshGetAddress)(nil), "hw.trezor.messages.xcosh.XcoshGetAddress")
	proto.RegisterType((*XcoshAddress)(nil), "hw.trezor.messages.xcosh.XcoshAddress")
	proto.RegisterType((*XcoshSignTx)(nil), "hw.trezor.messages.xcosh.XcoshSignTx")
	proto.RegisterType((*XcoshTxRequest)(nil), "hw.trezor.messages.xcosh.XcoshTxRequest")
	proto.RegisterType((*XcoshTxAck)(nil), "hw.trezor.messages.xcosh.XcoshTxAck")
	proto.RegisterType((*XcoshSignMessage)(nil), "hw.trezor.messages.xcosh.XcoshSignMessage")
	proto.RegisterType((*XcoshMessageSignature)(nil), "hw.trezor.messages.xcosh.XcoshMessageSignature")
	proto.RegisterType((*XcoshVerifyMessage)(nil), "hw.trezor.messages.xcosh.XcoshVerifyMessage")
}

func init() { proto.RegisterFile("messages-xcosh.proto", fileDescriptor_cb33f46ba915f15c) }

var fileDescriptor_cb33f46ba915f15c = []byte{
	// 593 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x95, 0x9b, 0xb4, 0x49, 0x26, 0x0d, 0x1f, 0xa6, 0x55, 0x17, 0x0a, 0x34, 0x18, 0x21, 0xe5,
	0x00, 0x3e, 0x70, 0x43, 0xe2, 0xd2, 0x52, 0x44, 0x2b, 0x4a, 0x55, 0xdc, 0xa8, 0x57, 0x6b, 0x63,
	0x6f, 0xe3, 0x55, 0x9d, 0xdd, 0xe0, 0x5d, 0xb7, 0x0e, 0x7f, 0x82, 0x23, 0xff, 0x87, 0x5f, 0x86,
	0xf6, 0x2b, 0x71, 0x52, 0x54, 0x0e, 0xbd, 0x65, 0xde, 0xbc, 0x7d, 0xf3, 0x66, 0xf4, 0x62, 0xd8,
	0x99, 0x10, 0x21, 0xf0, 0x98, 0x88, 0x77, 0x44, 0x66, 0xa4, 0x20, 0xe5, 0x24, 0x9c, 0x16, 0x5c,
	0x72, 0x7f, 0x37, 0xbb, 0x09, 0x65, 0x41, 0x7e, 0xf2, 0x22, 0x74, 0x94, 0xd0, 0x51, 0x9e, 0x6d,
	0xcf, 0x5f, 0x25, 0x7c, 0x32, 0xe1, 0xcc, 0xbc, 0x09, 0x2e, 0x60, 0xeb, 0xb3, 0xa5, 0x7c, 0x21,
	0xf2, 0xac, 0x1c, 0xe5, 0x34, 0xf9, 0x4a, 0x66, 0xfe, 0x2e, 0x74, 0x70, 0x9a, 0x16, 0x44, 0x88,
	0x98, 0x21, 0xaf, 0xdf, 0x18, 0xf4, 0xa2, 0xb6, 0x05, 0x4e, 0xfd, 0x57, 0xb0, 0x29, 0x32, 0x7e,
	0x13, 0xa7, 0x54, 0x4c, 0x73, 0x3c, 0x43, 0x6b, 0x7d, 0x6f, 0xd0, 0x8e, 0xba, 0x0a, 0x3b, 0x34,
	0x50, 0x30, 0x82, 0xc7, 0x4e, 0x77, 0x21, 0xfa, 0x01, 0x9a, 0x8c, 0xa7, 0x04, 0x79, 0x7d, 0x6f,
	0xd0, 0x7d, 0xff, 0x26, 0xfc, 0x87, 0x5f, 0x6b, 0xee, 0xe8, 0xf0, 0x94, 0xa7, 0x64, 0x38, 0x9b,
	0x92, 0x48, 0x3f, 0xf1, 0x7d, 0x68, 0x56, 0xd3, 0x72, 0xa4, 0x47, 0x75, 0x22, 0xfd, 0x3b, 0x18,
	0x82, 0x5f, 0xf3, 0xbe, 0x6f, 0xdc, 0xdd, 0xdb, 0xf9, 0x77, 0x78, 0xe8, 0x54, 0x9d, 0xe4, 0x4b,
	0x00, 0xab, 0x70, 0x40, 0x99, 0x76, 0xbf, 0x19, 0xd5, 0x90, 0x5a, 0xff, 0x88, 0x54, 0xd6, 0x62,
	0x0d, 0x09, 0xfe, 0xac, 0xc1, 0x03, 0xa7, 0x79, 0x4e, 0xc7, 0x6c, 0x58, 0xdd, 0xed, 0x72, 0x0b,
	0xd6, 0x19, 0x67, 0x09, 0xd1, 0x52, 0x9b, 0x91, 0x29, 0xd4, 0x93, 0x31, 0x16, 0xf1, 0xb4, 0xa0,
	0x09, 0x41, 0x0d, 0xdd, 0x69, 0x8f, 0xb1, 0x38, 0x53, 0xb5, 0x6b, 0xe6, 0x74, 0x42, 0x25, 0x6a,
	0xce, 0x9b, 0x27, 0xaa, 0x56, 0x7a, 0x92, 0x2b, 0xeb, 0xeb, 0x46, 0x4f, 0x17, 0x06, 0x55, 0x86,
	0xbb, 0xda, 0xb0, 0x29, 0x14, 0x7a, 0x8d, 0xf3, 0x92, 0xa0, 0x0d, 0xc3, 0xd5, 0x85, 0xff, 0x16,
	0xfc, 0x14, 0x4b, 0x1c, 0x53, 0x46, 0x25, 0xc5, 0x79, 0x9c, 0x64, 0x25, 0xbb, 0x42, 0x2d, 0x4d,
	0x79, 0xa4, 0x3a, 0xc7, 0xa6, 0xf1, 0x49, 0xe1, 0xfe, 0x1e, 0x74, 0x35, 0x3b, 0x27, 0x6c, 0x2c,
	0x33, 0xd4, 0xee, 0x7b, 0x83, 0x5e, 0x04, 0x0a, 0x3a, 0xd1, 0x88, 0xff, 0x14, 0xda, 0x49, 0x86,
	0x29, 0x8b, 0x69, 0x8a, 0x3a, 0xba, 0xdb, 0xd2, 0xf5, 0x71, 0xea, 0xef, 0x40, 0x4b, 0x56, 0xb1,
	0x9c, 0x4d, 0x09, 0x02, 0xdd, 0xd9, 0x90, 0x95, 0xca, 0x41, 0xf0, 0xdb, 0x5b, 0x44, 0x6a, 0x58,
	0x45, 0xe4, 0x47, 0x49, 0x84, 0x5c, 0x1d, 0xe5, 0xdd, 0x1a, 0xb5, 0x07, 0x5d, 0x41, 0xc7, 0x0c,
	0xcb, 0xb2, 0x20, 0xf1, 0xb5, 0xbe, 0x68, 0x2f, 0x82, 0x39, 0x74, 0xb1, 0x4c, 0x28, 0xec, 0x61,
	0x17, 0x84, 0x68, 0x99, 0x20, 0xec, 0x71, 0x17, 0x84, 0xf3, 0x20, 0x84, 0xde, 0xc2, 0xd8, 0x7e,
	0x72, 0xe5, 0xbf, 0x00, 0xed, 0xc0, 0x5e, 0xc9, 0xe4, 0xa5, 0xa3, 0x10, 0x7d, 0x9e, 0xe0, 0x04,
	0x9e, 0xd4, 0xd3, 0xf0, 0xcd, 0x64, 0xff, 0xee, 0x48, 0x20, 0x68, 0xd9, 0xff, 0x88, 0x0d, 0x85,
	0x2b, 0x83, 0x0a, 0x90, 0x53, 0xb3, 0x4a, 0xe7, 0xce, 0xda, 0x7f, 0x83, 0xfb, 0x1c, 0x3a, 0xf3,
	0x3d, 0xac, 0xee, 0x02, 0x58, 0x89, 0x75, 0xe3, 0x56, 0xac, 0x7f, 0x79, 0xb0, 0xed, 0x46, 0x5f,
	0x90, 0x82, 0x5e, 0xce, 0xdc, 0x2a, 0xf7, 0x9b, 0x5b, 0xdb, 0xb5, 0xb1, 0xb4, 0xeb, 0x8a, 0xa3,
	0xe6, 0xaa, 0xa3, 0x83, 0x8f, 0xf0, 0x3a, 0xe1, 0x93, 0x50, 0x60, 0xc9, 0x45, 0x46, 0x73, 0x3c,
	0x12, 0xee, 0x03, 0x93, 0xd3, 0x91, 0xf9, 0xe2, 0x8d, 0xca, 0xcb, 0x83, 0xed, 0xa1, 0x06, 0xad,
	0x5b, 0xb7, 0xc2, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8a, 0xce, 0x81, 0xc8, 0x59, 0x05, 0x00,
	0x00,
}
