name: Benchmark Core
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  bench_core_geth:
    name: Benchmark core-geth
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Set up Go 1.x
        id: go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Benchmark etclabscore/core-geth
        id: bench
        run: |
          go test -short ./core -count 1 -p 1 -timeout 60m -run NONE -bench=. -v |& tee core-geth.txt

      - uses: actions/upload-artifact@v4
        with:
          name: core-geth
          path: ./core-geth.txt

  bench_go_xcosh:
    name: Benchmark go-xcosh
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Set up Go 1.x
        id: go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          repository: 'xcosh/go-xcosh'
          ref: 'v1.10.26'

      - name: Benchmark xcosh/go-xcosh
        id: bench
        run: |
          go test -short ./core -count 1 -p 1 -timeout 60m -run NONE -bench=. -v |& tee go-xcosh.txt

      - uses: actions/upload-artifact@v4
        with:
          name: go-xcosh
          path: ./go-xcosh.txt

  compare:
    name: Compare
    needs: [bench_core_geth, bench_go_xcosh]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Set up Go 1.x
        id: go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go install golang.org/x/perf/cmd/benchstat@latest

      - uses: actions/download-artifact@v4
        name: Get go-xcosh artifact
        with:
          name: go-xcosh

      - uses: actions/download-artifact@v4
      - uses: actions/download-artifact@v4
        name: Get core-geth artifact
        with:
          name: core-geth

      - name: "Analyze Results [COMPRESSED]"
        run: |
          benchstat go-xcosh.txt core-geth.txt

      - name: "Analyze Results [RAW DELTA]"
        run: |
          benchstat go-xcosh.txt core-geth.txt
